require 'string'

global GenerationalIndex = @record{
   index: isize,
   generation: uinteger
}

function GenerationalIndex.__eq(gidx1: GenerationalIndex, gidx2: GenerationalIndex) <inline>
   return gidx1.index == gidx2.index and gidx1.generation == gidx2.generation
end

function GenerationalIndex:__tostring(): string
   return '(@GenerationalIndex){ index = ' .. self.index .. ', generation = ' .. self.generation .. '}'
end
